[workspace]
resolver = "2"
members = [
  "addressbook-lib",
  "addressbook-std",
  "addressbook-std-rustls",
]

[patch.crates-io]
addressbook.path = "./addressbook-lib"
addressbook-std.path = "./addressbook-std"
addressbook-std-rustls.path = "./addressbook-std-rustls"
