[workspace]
resolver = "2"
members = [
  "addressbook-lib",
  "addressbook-carddav",
  "addressbook-carddav-rustls",
  "addressbook-carddav-native-tls",
]

[patch.crates-io]
addressbook.path = "./addressbook-lib"
addressbook-carddav.path = "./addressbook-carddav"
addressbook-carddav-rustls.path = "./addressbook-carddav-rustls"
addressbook-carddav-native-tls.path = "./addressbook-carddav-native-tls"
