[package]
name = "cardamum"
description = "CLI to manage contacts"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["cli", "contact", "addressbook", "carddav", "webdav"]
homepage = "https://pimalaya.org/"
documentation = "https://github.com/pimalaya/cardamum/"
repository = "https://github.com/pimalaya/cardamum/"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dev-dependencies]
cardamum = { path = ".", features = [] }

[build-dependencies]
pimalaya-tui = { version = "0.2", default-features = false, features = ["build-envs"] }

[dependencies]
base64 = { version = "0.22", features = [] }
chrono = { version = "0.4", features = [] }
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
clap_complete = { version = "4.4", features = [] }
clap_mangen = { version = "0.2", features = [] }
color-eyre = { version = "0.6", features = [] }
memchr = { version = "2.7.4", features = [] }
pimalaya-tui = { version = "0.2", default-features = false, features = ["cli", "config", "path", "tracing"] }
quick-xml = { version = "0.37", features = ["serialize"] }
rustls = { version = "0.23", features = [] }
rustls-platform-verifier = { version = "0.5", features = [] }
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2", features = [] }
tracing = { version = "0.1", features = [] }

[patch.crates-io]
pimalaya-tui.git = "https://github.com/pimalaya/tui"
